name: Github Actions - Push branches ignore template basic
run-name: Running - ${{ github.event_name }}
on: 
  push:
    branches-ignore:
      - main

jobs:
  on-push:
    runs-on:   ubuntu-latest
    steps:
      - name: Coment√°rio
        run: |
          echo "Ignorando o branch main"
